#ifndef LORA32_CONFIG_H
	#define LORA32_CONFIG_H

	#define BOARD_LED_0 25

	#define SDCARD_MISO_PIN 2
	#define SDCARD_MOSI_PIN 15
	#define SDCARD_CLK_PIN 14
	#define SDCARD_CS_PIN 13

	#define I2C_SDA_PIN GPIO_NUM_21
	#define I2C_SCL_PIN GPIO_NUM_22

	#define B20_DATA_PIN GPIO_NUM_4

#endif
